# Generated by Django 4.2.2 on 2023-10-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_price',
            new_name='subtotal',
        ),
    ]
